version: '3.8'

services:
  mysql:
    image: mysql:5.7.44
    container_name: pilast-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pilast
      MYSQL_USER: pilastuser
      MYSQL_PASSWORD: pilastpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
